name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: ECD011_TP_Grupo8.sln                         # O nome da sua solução
      Test_Project_Path: ECD011_TP_Grupo8Tests\ECD011_TP_Grupo8Tests.csproj   # O caminho para o seu projeto de testes

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Instala o .NET Core
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Adiciona MSBuild ao PATH
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Executa os testes unitários da solução
    - name: Execute unit tests
      run: dotnet test ${{ env.Test_Project_Path }}

    # Restaura a solução
    - name: Restore the solution
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    # Compila a solução
    - name: Build the solution
      run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    # Carrega os artefatos de build
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build Output
        path: path/to/your/build/output/folder
